# 1. Create a 3x3x3 array with random values 

In [2]:
import numpy as np
np.empty((3,3,3))

array([[[2.46876619e-316, 2.57400929e-316, 1.48219694e-323],
        [6.95058196e-310, 0.00000000e+000, 6.95058196e-310],
        [2.12199579e-314, 6.95058196e-310, 0.00000000e+000]],

       [[0.00000000e+000, 0.00000000e+000, 2.12199579e-311],
        [            nan, 2.12199579e-314, 4.94065646e-324],
        [4.94065646e-324, 0.00000000e+000, 6.95057401e-310]],

       [[2.57493457e-316, 2.12199579e-314, 2.57885034e-316],
        [2.47032823e-323, 4.94065646e-324, 0.00000000e+000],
        [6.95057401e-310, 6.95057401e-310, 4.94065646e-324]]])

# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [3]:
np.tril([[1,2,3,4],[1,2,3,4],[1,2,3,4],[1,2,3,4],[1,2,3,4]], -1)

array([[0, 0, 0, 0],
       [1, 0, 0, 0],
       [1, 2, 0, 0],
       [1, 2, 3, 0],
       [1, 2, 3, 4]])

# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [4]:
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1 # Start row from = 1 to end in the steps of two, start column start =0 to end in the steps of 2
x[::2,1::2] = 1 # Start from 0th row to end of row in step of 2, start from 1st col to end of the cols step of 2
x

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

# 4. Normalize a 5x5 random matrix

In [5]:

x = np.array([[1,2,3],[4,5,6],[7,8,9]])
xmax = x.max()
xmin = x.min()
x = (x-xmin)/(xmax-xmin)

# 5.  How to find common values between two arrays?

In [6]:
array1 = np.array([0, 10, 20, 40, 60])
print("Array1: ",array1)
array2 = [10, 30, 40]
print("Array2: ",array2)
print("Common values between two arrays:")
print(np.intersect1d(array1, array2))

Array1:  [ 0 10 20 40 60]
Array2:  [10, 30, 40]
Common values between two arrays:
[10 40]


# 6.How to get the dates of yesterday, today and tomorrow?

In [7]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2020-07-25
Today:  2020-07-26
Tomorrow:  2020-07-27


# 7. Consider two random array A and B, check if they are equal

# 8.Create random vector of size 10 and replace the maximum value by 0 

In [8]:
import numpy as np
x = np.random.random(10)
print("Original array:")
print(x)
x[x.argmax()] = 0


Original array:
[0.1098748  0.72033539 0.92109077 0.5880469  0.40643949 0.3476281
 0.87439939 0.39739092 0.70532901 0.41996163]


# 9. How to print all the values of an array?

In [9]:
# by prining name of array

# 10.Subtract the mean of each row of a matrix

In [10]:
# Question not understood
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
x.mean(axis=1)

array([2., 5., 8.])

# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [13]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)


[4. 2. 3. 1. 5. 3. 3. 5. 1. 3.]


# 12.How to get the diagonal of a dot product?

# 13.How to find the most frequent value in an array?

In [11]:
Z = np.random.randint(0,10,50)
print (Z)
print('rank:', np.bincount(Z).argmax())

[1 0 5 6 2 0 8 5 5 1 6 2 4 0 4 9 2 8 6 8 2 7 5 5 8 8 3 3 9 7 8 6 5 2 1 8 6
 1 7 9 1 7 9 6 9 4 0 8 8 6]
rank: 8


# 14.How to get the n largest values of an array

In [12]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

print (Z[np.argsort(Z)[-n:]])

[9995 9996 9997 9998 9999]


# 15.How to create a record array from a regular array?